# Generated by Django 5.0.6 on 2026-09-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_reg_no', models.CharField(db_index=True, max_length=20)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=20)),
                ('insurer_name', models.CharField(max_length=80)),
                ('plan_name', models.CharField(default='Comprehensive 2-Wheeler Package', max_length=100)),
                ('engine_capacity_cc', models.PositiveIntegerField()),
                ('idv_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ncb_percent', models.PositiveIntegerField(default=0)),
                ('od_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tp_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addons_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('selected_addons', models.JSONField(default=list)),
                ('net_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='RTOQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('sign_code', models.CharField(blank=True, max_length=60, null=True)),
                ('category', models.CharField(default='Mandatory Signs', max_length=60)),
                ('options', models.JSONField(help_text='List of 4 answer options')),
                ('correct_index', models.PositiveIntegerField(help_text='0-indexed position of correct answer')),
                ('explanation', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('masked_owner', models.CharField(max_length=100)),
                ('maker_model', models.CharField(max_length=120)),
                ('vehicle_class', models.CharField(default='M-Cycle/Scooter(2WN)', max_length=60)),
                ('fuel_type', models.CharField(default='PETROL', max_length=30)),
                ('engine_capacity_cc', models.PositiveIntegerField(help_text='Displacement in Cubic Centimeters')),
                ('registration_date', models.DateField()),
                ('fitness_upto', models.DateField()),
                ('insurance_upto', models.DateField()),
                ('pucc_upto', models.DateField(blank=True, null=True)),
                ('rto_office', models.CharField(max_length=120)),
                ('chassis_number_masked', models.CharField(default='MD625...8841', max_length=50)),
                ('engine_number_masked', models.CharField(default='JE35E...2190', max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('violation_title', models.CharField(max_length=200)),
                ('violation_description', models.TextField()),
                ('offense_date', models.DateTimeField()),
                ('offense_place', models.CharField(max_length=200)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='api.vehicle')),
            ],
        ),
    ]
