# Generated by Django 5.0.14 on 2026-09-14 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vehicle_reg_no', models.CharField(db_index=True, max_length=20)),
                ('claim_type', models.CharField(choices=[('CASHLESS', 'Cashless Claim'), ('REIMBURSEMENT', 'Reimbursement Claim')], default='CASHLESS', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Under Review'), ('APPROVED', 'Surveyor Approved'), ('REJECTED', 'Claim Rejected'), ('SETTLED', 'Settled & Paid')], default='PENDING', max_length=30)),
                ('accident_date', models.DateField()),
                ('accident_place', models.CharField(max_length=200)),
                ('accident_description', models.TextField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_license_no', models.CharField(max_length=50)),
                ('fir_filed', models.BooleanField(default=False)),
                ('fir_number', models.CharField(blank=True, max_length=50, null=True)),
                ('workshop_name', models.CharField(default='Authorized Network Workshop', max_length=150)),
                ('workshop_type', models.CharField(default='NETWORK_CASHLESS', max_length=30)),
                ('is_rc_submitted', models.BooleanField(default=True)),
                ('is_dl_submitted', models.BooleanField(default=True)),
                ('is_policy_submitted', models.BooleanField(default=True)),
                ('is_estimate_submitted', models.BooleanField(default=True)),
                ('claimed_parts', models.JSONField(default=list, help_text='List of damaged parts with name, category, claimed amount, depreciation, and approved amount')),
                ('claimed_labour_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_claimed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('depreciation_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('compulsory_excess', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_approved_parts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_approved_labour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('approved_settlement_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customer_liability', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('surveyor_name', models.CharField(default='K. Srinivasan (IRDAI Lic #77419)', max_length=100)),
                ('surveyor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='api.policy')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='api.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
